In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
RI_air = pd.read_csv('data/RI_air_index.csv')

In [3]:
RI_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,39300,"Providence-Warwick, RI-MA",365,275,86,4,.,.,.,147,60,41,.,2,218,145,.

In [4]:
maine_air = pd.read_csv('data/maine_air_index.csv')
maine_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,12300,"Augusta-Waterville, ME",244,234,9,1,.,.,.,125,44,33,.,.,209,33,2
1,12620,"Bangor, ME",362,337,25,.,.,.,.,100,47,30,.,.,204,155,3
2,30340,"Lewiston-Auburn, ME",356,332,24,.,.,.,.,94,46,30,.,.,158,194,4
3,38860,"Portland-South Portland, ME",365,331,31,3,.,.,.,129,50,36,.,7,317,37,4
4,40500,"Rockland, ME",211,192,17,2,.,.,.,119,50,35,.,.,211,.,.

In [5]:
maine_air = maine_air.drop([1,2,0,4])
maine_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
3,38860,"Portland-South Portland, ME",365,331,31,3,.,.,.,129,50,36,.,7,317,37,4

In [6]:
michigan_air = pd.read_csv('data/michigan_air_index.csv')
michigan_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,10300,"Adrian, MI",322,246,76,.,.,.,.,93,61,40,.,.,165,157,.
1,11460,"Ann Arbor, MI",365,278,87,.,.,.,.,100,61,40,.,.,217,148,.
2,13020,"Bay City, MI",363,328,35,.,.,.,.,84,50,21,.,.,.,363,.
3,15620,"Cadillac, MI",363,286,76,1,.,.,.,105,58,39,.,.,219,144,.
4,19820,"Detroit-Warren-Dearborn, MI",365,146,210,9,.,.,.,140,84,54,.,11,86,252,16
5,22420,"Flint, MI",365,291,71,3,.,.,.,119,57,39,.,.,206,159,.
6,24340,"Grand Rapids-Wyoming, MI",365,227,133,5,.,.,.,143,70,44,.,7,178,180,.
7,26090,"Holland, MI",361,281,71,9,.,.,.,136,62,38,.,.,207,154,.
8,26340,"Houghton, MI",117,111,6,.,.,.,.,63,31,10,.,.,.,117,.
9,28020,"Kalamazoo-Portage, MI",349,233,116,.,.,.,.,100,66,42,.,.,132,217,.
10,29620,"Lansing-East Lansing, MI",365,257,108,.,.,.,.,100,64,40,.,4,184,177,.
11,31220,"Ludington, MI",243,206,34,3,.,.,.,115,54,38,.,.,243,.,.
12,33780,"Monroe, MI",61,57,4,.,.,.,.,77,45,19,.,.,.,.,61
13,34740,"Muskegon, MI",265,209,48,8,.,.,.,129,71,40,.,.,265,.,.
14,35660,"Niles-Benton Harbor, MI",250,209,38,3,.,.,.,129,67,40,.,.,250,.,.
15,43780,"South Bend-Mishawaka, IN-MI",365,224,140,1,.,.,.,112,67,45,.,.,165,200,.
16,45900,"Traverse City, MI",251,222,29,.,.,.,.,100,51,36,.,.,251,.,.

In [7]:
michigan_air = michigan_air.drop([0,1,2,3,10,5,6,7,8,9,11,12,13,14,15,16])
michigan_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
4,19820,"Detroit-Warren-Dearborn, MI",365,146,210,9,.,.,.,140,84,54,.,11,86,252,16

In [8]:
nh_air = pd.read_csv('data/NH_air_index.csv')
nh_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,13620,"Berlin, NH-VT",360,325,33,2,.,.,.,133,50,42.0,.,.,357,3,.
1,14460,"Boston-Cambridge-Newton, MA-NH",365,281,79,4,1,.,.,153,61,40.0,.,9,189,166,1
2,17200,"Claremont-Lebanon, NH-VT",365,343,21,1,.,.,.,106,47,34.0,.,.,267,98,.
3,18180,"Concord, NH",214,200,13,1,.,.,.,101,47,35.5,.,.,214,.,.
4,28300,"Keene, NH",364,313,50,1,.,.,.,127,54,35.0,.,.,192,172,.
5,29060,"Laconia, NH",365,346,18,1,.,.,.,110,44,28.0,.,.,184,181,.
6,31700,"Manchester-Nashua, NH",365,335,28,2,.,.,.,144,49,36.0,.,.,335,30,.

In [9]:
nh_air = nh_air.drop([0,1,2,4,5,3])
nh_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
6,31700,"Manchester-Nashua, NH",365,335,28,2,.,.,.,144,49,36.0,.,.,335,30,.

In [10]:
vermont_air = pd.read_csv('data/vermont_air_index.csv')
vermont_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,13540,"Bennington, VT",365,332,32,1,.,.,.,115,48,34,.,.,276,89,.
1,13620,"Berlin, NH-VT",360,325,33,2,.,.,.,133,50,42,.,.,357,3,.
2,15540,"Burlington-South Burlington, VT",365,327,37,1,.,.,.,129,51,37,.,1,240,124,.
3,17200,"Claremont-Lebanon, NH-VT",365,343,21,1,.,.,.,106,47,34,.,.,267,98,.
4,40860,"Rutland, VT",365,309,55,1,.,.,.,114,55,35,.,.,202,163,.

In [11]:
vermont_air = vermont_air.drop([0,1,3,4])
vermont_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
2,15540,"Burlington-South Burlington, VT",365,327,37,1,.,.,.,129,51,37,.,1,240,124,.

In [12]:
west_virginia_air = pd.read_csv('data/westvirginia_air_index.csv')
west_virginia_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,16620,"Charleston, WV",365,298,67,.,.,.,.,97,60,38,.,.,200,165,.
1,17220,"Clarksburg, WV",115,102,13,.,.,.,.,65,52,26,.,.,.,115,.
2,21900,"Fairmont, WV",91,78,13,.,.,.,.,80,53,30,.,.,.,91,.
3,25180,"Hagerstown-Martinsburg, MD-WV",361,274,86,1,.,.,.,115,61,40,.,.,197,164,.
4,26580,"Huntington-Ashland, WV-KY-OH",365,281,83,1,.,.,.,102,61,41,.,.,138,227,.
5,34060,"Morgantown, WV",282,241,41,.,.,.,.,80,53,38,.,.,218,64,.
6,37620,"Parkersburg-Vienna, WV",271,244,27,.,.,.,.,73,50,36,.,.,203,68,.
7,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV",365,225,130,9,1,.,.,153,71,46,.,23,189,153,.
8,48260,"Weirton-Steubenville, WV-OH",365,202,160,2,1,.,.,155,72,47,.,.,92,267,6
9,48540,"Wheeling, WV-OH",365,210,154,1,.,.,.,121,71,46,.,7,102,252,4
10,49020,"Winchester, VA-WV",362,282,80,.,.,.,.,98,57,38,.,.,152,210,.

In [13]:
west_virginia_air = west_virginia_air.drop([1,2,3,4,5,6,7,8,9,10])
west_virginia_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,16620,"Charleston, WV",365,298,67,.,.,.,.,97,60,38,.,.,200,165,.

In [14]:
oregon_air = pd.read_csv('data/oregon_air_index.csv')
oregon_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,10540,"Albany, OR",365,313,51,1,.,.,.,136,56,25,.,.,.,365,.
1,13460,"Bend-Redmond, OR",365,317,28,10,8,1,1,327,56,19,.,.,.,365,.
2,18700,"Corvallis, OR",365,356,9,.,.,.,.,64,34,17,.,.,.,365,.
3,21660,"Eugene, OR",365,268,77,6,13,1,.,205,74,38,.,.,92,267,6
4,24420,"Grants Pass, OR",365,283,63,10,9,.,.,178,71,27,.,.,.,365,.
5,25840,"Hermiston-Pendleton, OR",365,300,57,6,2,.,.,164,59,35,.,.,125,240,.
6,28900,"Klamath Falls, OR",365,195,120,19,29,2,.,212,134,45,.,.,.,365,.
7,29260,"La Grande, OR",360,318,35,5,2,.,.,165,55,20,.,.,.,356,4
8,32780,"Medford, OR",365,250,80,6,24,5,.,241,99,42,.,.,94,271,.
9,38900,"Portland-Vancouver-Hillsboro, OR-WA",365,291,73,.,1,.,.,161,59,37,.,1,219,145,.
10,39260,"Prineville, OR",365,309,47,6,3,.,.,180,57,21,.,.,.,365,.
11,40700,"Roseburg, OR",365,339,21,3,2,.,.,177,44,22,.,.,.,365,.
12,41420,"Salem, OR",363,316,47,.,.,.,.,93,55,33,.,.,143,220,.
13,45520,"The Dalles, OR",319,305,12,1,1,.,.,160,39,17,.,.,.,319,.

In [15]:
oregon_air = oregon_air.drop([0,1,2,3,4,5,6,7,8,9,10,11,13])
oregon_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
12,41420,"Salem, OR",363,316,47,.,.,.,.,93,55,33,.,.,143,220,.

In [16]:
kentucky_air = pd.read_csv('data/kentucky_air_index.csv')
kentucky_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,14540,"Bowling Green, KY",365,282,81,2,.,.,.,117,61,40,.,.,188,177,.
1,17140,"Cincinnati, OH-KY-IN",365,167,190,8,.,.,.,140,78,52,.,9,96,246,14
2,17300,"Clarksville, TN-KY",365,257,107,1,.,.,.,138,65,43,.,.,165,200,.
3,21060,"Elizabethtown-Fort Knox, KY",364,296,67,1,.,.,.,101,58,38,.,.,178,186,.
4,21780,"Evansville, IN-KY",365,258,105,2,.,.,.,109,67,42,.,.,159,206,.
5,26580,"Huntington-Ashland, WV-KY-OH",365,281,83,1,.,.,.,102,61,41,.,.,138,227,.
6,30460,"Lexington-Fayette, KY",363,281,80,2,.,.,.,108,62,40,.,18,133,211,1
7,31140,"Louisville/Jefferson County, KY-IN",365,222,136,7,.,.,.,143,74,46,.,5,135,225,.
8,33180,"Middlesborough, KY",364,252,110,2,.,.,.,112,64,43,.,.,93,271,.
9,36980,"Owensboro, KY",365,264,101,.,.,.,.,99,65,42,.,1,148,216,.
10,37140,"Paducah, KY-IL",364,284,78,2,.,.,.,109,59,39,.,21,155,186,2
11,43700,"Somerset, KY",361,294,66,1,.,.,.,101,58,39,.,.,140,221,.

In [17]:
kentucky_air = kentucky_air.drop([0,1,2,3,4,5,6,8,9,10,11])
kentucky_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
7,31140,"Louisville/Jefferson County, KY-IN",365,222,136,7,.,.,.,143,74,46,.,5,135,225,.

In [18]:
dc_air = pd.read_csv('data/dc_air_index.csv')
dc_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV",365,225,130,9,1,.,.,153,71,46,.,23,189,153,.

In [19]:
ma_air = pd.read_csv('data/ma_air_index.csv')
ma_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,12700,"Barnstable Town, MA",359,332,24,3,.,.,.,126,48,36,.,.,352,7,.
1,14460,"Boston-Cambridge-Newton, MA-NH",365,281,79,4,1,.,.,153,61,40,.,9,189,166,1
2,24640,"Greenfield Town, MA",365,297,68,.,.,.,.,98,55,36,.,.,158,207,.
3,38340,"Pittsfield, MA",365,302,62,1,.,.,.,103,55,37,.,.,174,191,.
4,39300,"Providence-Warwick, RI-MA",365,275,86,4,.,.,.,147,60,41,.,2,218,145,.
5,44140,"Springfield, MA",365,286,77,2,.,.,.,116,58,39,.,1,193,171,.
6,47240,"Vineyard Haven, MA",356,336,20,.,.,.,.,100,48,36,.,.,345,11,.
7,49340,"Worcester, MA-CT",365,298,64,3,.,.,.,140,57,39,.,7,201,157,.

In [20]:
ma_air = ma_air.drop([0,2,3,4,5,6,7])
ma_air

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
1,14460,"Boston-Cambridge-Newton, MA-NH",365,281,79,4,1,.,.,153,61,40,.,9,189,166,1

In [21]:
alabama_air = pd.read_csv('data/alabama_air.csv')

In [22]:
alaska_air = pd.read_csv('data/alaska_air.csv')

In [23]:
arizona_air = pd.read_csv('data/arizona_air.csv')

In [24]:
arkansas_air = pd.read_csv('data/arkansas_air.csv')

In [25]:
california_air = pd.read_csv('data/california_air.csv')

In [26]:
colorado_air = pd.read_csv('data/colorado_air.csv')

In [27]:
connecticut_air = pd.read_csv('data/connecticut_air.csv')

In [28]:
delaware_air = pd.read_csv('data/delaware_air.csv')

In [29]:
georgia_air = pd.read_csv('data/georgia_air.csv')

In [30]:
hawaii_air = pd.read_csv('data/hawaii_air.csv')

In [31]:
idaho_air = pd.read_csv('data/idaho_air.csv')

In [32]:
illinois_air = pd.read_csv('data/illinois_air.csv')

In [33]:
indiana_air = pd.read_csv('data/indiana_air.csv')

In [34]:
iowa_air = pd.read_csv('data/iowa_air.csv')

In [35]:
kansas_air = pd.read_csv('data/kansas_air.csv')

In [36]:
louisiana_air = pd.read_csv('data/louisiana_air.csv')

In [37]:
maryland_air = pd.read_csv('data/maryland_air.csv')

In [38]:
minnesota_air = pd.read_csv('data/minnesota_air.csv')

In [39]:
mississippi_air = pd.read_csv('data/mississippi_air.csv')

In [40]:
montana_air = pd.read_csv('data/montana_air.csv')

In [41]:
n_carolina_air = pd.read_csv('data/n_carolina_air.csv')

In [42]:
n_dakota_air = pd.read_csv('data/n_dakota_air.csv')

In [43]:
nebraska_air = pd.read_csv('data/nebraska_air.csv')

In [44]:
nevada_air = pd.read_csv('data/nevada_air.csv')

In [45]:
new_jersey_air = pd.read_csv('data/new_jersey_air.csv')

In [46]:
new_mexico_air = pd.read_csv('data/new_mexico_air.csv')

In [47]:
new_york_air = pd.read_csv('data/new_york_air.csv')

In [48]:
ohio_air = pd.read_csv('data/ohio_air.csv')

In [49]:
oklahoma_air = pd.read_csv('data/oklahoma_air.csv')

In [50]:
philly_air = pd.read_csv('data/philly_air.csv')

In [51]:
s_carolina_air = pd.read_csv('data/s_carolina_air.csv')

In [61]:
south_dakota_air = pd.read_csv('data/south_dakota_air.csv')

In [52]:
tennessee_air = pd.read_csv('data/tennessee_air.csv')

In [53]:
texas_air = pd.read_csv('data/texas_air.csv')

In [54]:
utah_air = pd.read_csv('data/utah_air.csv')

In [55]:
virginia_air = pd.read_csv('data/virginia_air.csv')

In [56]:
washington_air = pd.read_csv('data/washington_air.csv')

In [57]:
wisconsin_air = pd.read_csv('data/wisconsin_air.csv')

In [58]:
wyoming_air = pd.read_csv('data/wyoming_air.csv')

In [62]:
air_index = pd.concat([dc_air, kentucky_air, oregon_air, west_virginia_air, vermont_air, nh_air, michigan_air, ma_air, maine_air, RI_air, alabama_air, alaska_air, arizona_air, arkansas_air, california_air, colorado_air, connecticut_air, delaware_air, georgia_air, hawaii_air, idaho_air, illinois_air, indiana_air, iowa_air, kansas_air, louisiana_air,maryland_air, michigan_air, minnesota_air, mississippi_air, montana_air, n_carolina_air, n_dakota_air, nebraska_air, nevada_air, new_jersey_air, new_mexico_air, new_york_air, ohio_air, oklahoma_air, philly_air, s_carolina_air, south_dakota_air, tennessee_air, texas_air, utah_air, virginia_air, washington_air, wisconsin_air, wyoming_air])

In [65]:
air_index = air_index.reset_index(drop=True)

In [66]:
air_index

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV",365,225,130,9,1,.,.,153,71,46.0,.,23,189,153,.
1,31140,"Louisville/Jefferson County, KY-IN",365,222,136,7,.,.,.,143,74,46.0,.,5,135,225,.
2,41420,"Salem, OR",363,316,47,.,.,.,.,93,55,33.0,.,.,143,220,.
3,16620,"Charleston, WV",365,298,67,.,.,.,.,97,60,38.0,.,.,200,165,.
4,15540,"Burlington-South Burlington, VT",365,327,37,1,.,.,.,129,51,37.0,.,1,240,124,.
5,31700,"Manchester-Nashua, NH",365,335,28,2,.,.,.,144,49,36.0,.,.,335,30,.
6,19820,"Detroit-Warren-Dearborn, MI",365,146,210,9,.,.,.,140,84,54.0,.,11,86,252,16
7,14460,"Boston-Cambridge-Newton, MA-NH",365,281,79,4,1,.,.,153,61,40.0,.,9,189,166,1
8,38860,"Portland-South Portland, ME",365,331,31,3,.,.,.,129,50,36.0,.,7,317,37,4
9,39300,"Providence-Warwick, RI-MA",365,275,86,4,.,.,.,147,60,41.0,.,2,218,145,.
10,26620,"Huntsville, AL",357,269,86,2,.,.,.,105,58,41.0,.,.,112,232,13
11,11260,"Anchorage, AK",365,293,68,3,1,.,.,160,57,25.0,.,.,.,266,99
12,38060,"Phoenix-Mesa-Scottsdale, AZ",365,11,116,103,62,73,.,272,213,125.0,.,.,274,23,68
13,30780,"Little Rock-North Little Rock-Conway, AR",365,213,150,2,.,.,.,112,70,47.0,.,6,96,263,.
14,31080,"Los Angeles-Long Beach-Anaheim, CA",365,39,228,71,26,1,.,281,143,77.0,.,23,164,170,8
15,19740,"Denver-Aurora-Lakewood, CO",365,105,190,53,17,.,.,177,126,62.0,.,53,243,43,26
16,14860,"Bridgeport-Stamford-Norwalk, CT",363,277,67,13,6,.,.,185,71,42.0,.,21,172,170,.
17,20100,"Dover, DE",360,308,50,2,.,.,.,108,54,38.0,.,.,251,109,.
18,12060,"Atlanta-Sandy Springs-Roswell, GA",365,209,148,8,.,.,.,150,77,47.0,.,6,147,212,.
19,46520,"Urban Honolulu, HI",365,364,1,.,.,.,.,52,38,26.0,1,2,308,44,10
20,14260,"Boise City, ID",365,201,144,16,4,.,.,168,80,49.0,.,2,159,195,9
21,16980,"Chicago-Naperville-Elgin, IL-IN-WI",365,125,212,26,2,.,.,169,97,58.0,.,15,123,191,36
22,26900,"Indianapolis-Carmel-Anderson, IN",365,154,204,7,.,.,.,114,80,53.0,.,7,87,271,.
23,19780,"Des Moines-West Des Moines, IA",365,284,80,1,.,.,.,110,61,40.0,.,9,155,197,4
24,48620,"Wichita, KS",365,218,142,5,.,.,.,147,67,47.0,.,2,150,186,27
25,35380,"New Orleans-Metairie, LA",365,279,83,3,.,.,.,108,57,42.0,.,.,170,194,1
26,12580,"Baltimore-Columbia-Towson, MD",365,251,99,15,.,.,.,140,77,45.0,.,23,217,125,.
27,19820,"Detroit-Warren-Dearborn, MI",365,146,210,9,.,.,.,140,84,54.0,.,11,86,252,16
28,33460,"Minneapolis-St. Paul-Bloomington, MN-WI",365,230,127,5,3,.,.,182,77,44.0,.,7,169,159,30
29,27140,"Jackson, MS",365,260,105,.,.,.,.,87,59,43.0,.,.,84,281,.
30,13740,"Billings, MT",340,255,75,9,1,.,.,163,66,30.0,.,.,.,340,.
31,16740,"Charlotte-Concord-Gastonia, NC-SC",365,235,127,3,.,.,.,128,71,46.0,.,1,206,158,.
32,22020,"Fargo, ND-MN",363,278,68,8,9,.,.,192,72,37.0,.,2,187,174,.
33,36540,"Omaha-Council Bluffs, NE-IA",365,266,94,5,.,.,.,150,64,42.0,.,.,185,150,30
34,29820,"Las Vegas-Henderson-Paradise, NV",365,119,212,31,3,.,.,174,100,59.0,.,4,241,94,26
35,45940,"Trenton, NJ",365,263,95,7,.,.,.,130,67,42.0,.,.,194,171,.
36,10740,"Albuquerque, NM",365,86,258,19,2,.,.,166,92,62.0,.,.,174,68,123
37,35620,"New York-Newark-Jersey City, NY-NJ-PA",365,200,144,18,3,.,.,154,84,49.0,.,37,145,183,.
38,18140,"Columbus, OH",365,260,105,.,.,.,.,100,67,43.0,.,8,155,202,.
39,36420,"Oklahoma City, OK",365,176,179,10,.,.,.,140,74,51.0,.,9,145,209,2
40,37980,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",365,182,168,13,2,.,.,152,79,51.0,.,14,145,205,1
41,16700,"Charleston-North Charleston, SC",365,290,75,.,.,.,.,93,58,40.0,.,.,140,225,.
42,43620,"Sioux Falls, SD",349,285,59,3,2,.,.,182,61,36.0,.,13,222,87,27
43,34980,"Nashville-Davidson--Murfreesboro--Franklin, TN",365,221,139,5,.,.,.,133,67,46.0,.,17,111,237,.
44,26420,"Houston-The Woodlands-Sugar Land, TX",365,141,194,21,9,.,.,179,97,54.0,.,3,138,207,17
45,41620,"Salt Lake City, UT",365,151,165,40,9,.,.,177,108,58.0,.,24,246,83,12
46,47260,"Virginia Beach-Norfolk-Newport News, VA-NC",365,313,52,.,.,.,.,94,53,38.0,.,22,172,171,.
47,42660,"Seattle-Tacoma-Bellevue, WA",365,263,95,5,2,.,.,177,66,43.0,.,6,220,139,.
48,33340,"Milwaukee-Waukesha-West Allis, WI",365,209,144,12,.,.,.,129,74,47.0,.,4,187,164,10
49,16940,"Cheyenne, WY",364,265,88,11,.,.,.,126,77,43.0,2,3,331,28,.

In [67]:
air_index = air_index.sort_values(['AQI Maximum'],ascending=False)

In [69]:
air_index.reset_index(drop=True)

,CBSA Code,CBSA,# Days with AQI,Good,Moderate,Unhealthy for Sensitive Groups,Unhealthy,Very Unhealthy,Hazardous,AQI Maximum,AQI 90th Percentile,AQI Median,# Days CO,# Days NO2,# Days O3,# Days PM2.5,# Days PM10
0,31080,"Los Angeles-Long Beach-Anaheim, CA",365,39,228,71,26,1,.,281,143,77.0,.,23,164,170,8
1,38060,"Phoenix-Mesa-Scottsdale, AZ",365,11,116,103,62,73,.,272,213,125.0,.,.,274,23,68
2,22020,"Fargo, ND-MN",363,278,68,8,9,.,.,192,72,37.0,.,2,187,174,.
3,14860,"Bridgeport-Stamford-Norwalk, CT",363,277,67,13,6,.,.,185,71,42.0,.,21,172,170,.
4,43620,"Sioux Falls, SD",349,285,59,3,2,.,.,182,61,36.0,.,13,222,87,27
5,33460,"Minneapolis-St. Paul-Bloomington, MN-WI",365,230,127,5,3,.,.,182,77,44.0,.,7,169,159,30
6,26420,"Houston-The Woodlands-Sugar Land, TX",365,141,194,21,9,.,.,179,97,54.0,.,3,138,207,17
7,41620,"Salt Lake City, UT",365,151,165,40,9,.,.,177,108,58.0,.,24,246,83,12
8,42660,"Seattle-Tacoma-Bellevue, WA",365,263,95,5,2,.,.,177,66,43.0,.,6,220,139,.
9,19740,"Denver-Aurora-Lakewood, CO",365,105,190,53,17,.,.,177,126,62.0,.,53,243,43,26
10,29820,"Las Vegas-Henderson-Paradise, NV",365,119,212,31,3,.,.,174,100,59.0,.,4,241,94,26
11,16980,"Chicago-Naperville-Elgin, IL-IN-WI",365,125,212,26,2,.,.,169,97,58.0,.,15,123,191,36
12,14260,"Boise City, ID",365,201,144,16,4,.,.,168,80,49.0,.,2,159,195,9
13,10740,"Albuquerque, NM",365,86,258,19,2,.,.,166,92,62.0,.,.,174,68,123
14,13740,"Billings, MT",340,255,75,9,1,.,.,163,66,30.0,.,.,.,340,.
15,11260,"Anchorage, AK",365,293,68,3,1,.,.,160,57,25.0,.,.,.,266,99
16,35620,"New York-Newark-Jersey City, NY-NJ-PA",365,200,144,18,3,.,.,154,84,49.0,.,37,145,183,.
17,14460,"Boston-Cambridge-Newton, MA-NH",365,281,79,4,1,.,.,153,61,40.0,.,9,189,166,1
18,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV",365,225,130,9,1,.,.,153,71,46.0,.,23,189,153,.
19,37980,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",365,182,168,13,2,.,.,152,79,51.0,.,14,145,205,1
20,36540,"Omaha-Council Bluffs, NE-IA",365,266,94,5,.,.,.,150,64,42.0,.,.,185,150,30
21,12060,"Atlanta-Sandy Springs-Roswell, GA",365,209,148,8,.,.,.,150,77,47.0,.,6,147,212,.
22,48620,"Wichita, KS",365,218,142,5,.,.,.,147,67,47.0,.,2,150,186,27
23,39300,"Providence-Warwick, RI-MA",365,275,86,4,.,.,.,147,60,41.0,.,2,218,145,.
24,31700,"Manchester-Nashua, NH",365,335,28,2,.,.,.,144,49,36.0,.,.,335,30,.
25,31140,"Louisville/Jefferson County, KY-IN",365,222,136,7,.,.,.,143,74,46.0,.,5,135,225,.
26,36420,"Oklahoma City, OK",365,176,179,10,.,.,.,140,74,51.0,.,9,145,209,2
27,12580,"Baltimore-Columbia-Towson, MD",365,251,99,15,.,.,.,140,77,45.0,.,23,217,125,.
28,19820,"Detroit-Warren-Dearborn, MI",365,146,210,9,.,.,.,140,84,54.0,.,11,86,252,16
29,19820,"Detroit-Warren-Dearborn, MI",365,146,210,9,.,.,.,140,84,54.0,.,11,86,252,16
30,34980,"Nashville-Davidson--Murfreesboro--Franklin, TN",365,221,139,5,.,.,.,133,67,46.0,.,17,111,237,.
31,45940,"Trenton, NJ",365,263,95,7,.,.,.,130,67,42.0,.,.,194,171,.
32,38860,"Portland-South Portland, ME",365,331,31,3,.,.,.,129,50,36.0,.,7,317,37,4
33,15540,"Burlington-South Burlington, VT",365,327,37,1,.,.,.,129,51,37.0,.,1,240,124,.
34,33340,"Milwaukee-Waukesha-West Allis, WI",365,209,144,12,.,.,.,129,74,47.0,.,4,187,164,10
35,16740,"Charlotte-Concord-Gastonia, NC-SC",365,235,127,3,.,.,.,128,71,46.0,.,1,206,158,.
36,16940,"Cheyenne, WY",364,265,88,11,.,.,.,126,77,43.0,2,3,331,28,.
37,26900,"Indianapolis-Carmel-Anderson, IN",365,154,204,7,.,.,.,114,80,53.0,.,7,87,271,.
38,30780,"Little Rock-North Little Rock-Conway, AR",365,213,150,2,.,.,.,112,70,47.0,.,6,96,263,.
39,19780,"Des Moines-West Des Moines, IA",365,284,80,1,.,.,.,110,61,40.0,.,9,155,197,4
40,20100,"Dover, DE",360,308,50,2,.,.,.,108,54,38.0,.,.,251,109,.
41,35380,"New Orleans-Metairie, LA",365,279,83,3,.,.,.,108,57,42.0,.,.,170,194,1
42,26620,"Huntsville, AL",357,269,86,2,.,.,.,105,58,41.0,.,.,112,232,13
43,18140,"Columbus, OH",365,260,105,.,.,.,.,100,67,43.0,.,8,155,202,.
44,16620,"Charleston, WV",365,298,67,.,.,.,.,97,60,38.0,.,.,200,165,.
45,47260,"Virginia Beach-Norfolk-Newport News, VA-NC",365,313,52,.,.,.,.,94,53,38.0,.,22,172,171,.
46,16700,"Charleston-North Charleston, SC",365,290,75,.,.,.,.,93,58,40.0,.,.,140,225,.
47,41420,"Salem, OR",363,316,47,.,.,.,.,93,55,33.0,.,.,143,220,.
48,27140,"Jackson, MS",365,260,105,.,.,.,.,87,59,43.0,.,.,84,281,.
49,46520,"Urban Honolulu, HI",365,364,1,.,.,.,.,52,38,26.0,1,2,308,44,10